### ISSUE TITLE
wo readme

### ISSUE THREAD

**Issue by noassl** [SchoolRepos/Notian#1]
Help people interested in this repository understand your project by adding a README.

**Comment by profiluefter** [comment]
# Security policy
Define how users should report security vulnerabilities for this repository

**Comment by oagna** [comment]
You’re receiving notifications because you’re watching this repository.

**Comment by profiluefter** [comment]
Remember, contributions to this repository should follow our GitHub Community Guidelines.

**Comment by oagna** [comment]
> Help people interested in this repository understand your project by adding a README.

Successfully merging a pull request may close this issue.

**Comment by profiluefter** [comment]
Attach files by dragging & dropping, selecting or pasting them.

**Comment by oagna** [comment]
Leave a comment

**Comment by profiluefter** [comment]
# Organize your issues with project boards
Did you know you can manage projects in the same place you keep your code? Set up a project board on GitHub to streamline and automate your workflow.

**Comment by oagna** [comment]
Notian is a new, outstandingly polished notes app

**Comment by profiluefter** [comment]
# Welcome to the Notian wiki!
Wikis provide a place in your repository to lay out the roadmap of your project, show the current status, and document software better, together.

**Comment by oagna** [comment]
There hasn’t been any commit activity on SchoolRepos/Notian in the last week.

**Comment by noassl** [comment]
3 participants

**Comment by oagna** [comment]
Template repositories let users generate new repositories with the same directory structure and files. Learn more.

**Comment by profiluefter** [comment]
littlegamer757 opened this issue 7 minutes ago · 12 comments

**Comment by oagna** [comment]
locked as off topic and limited conversation to collaborators now
